# Generated by Django 5.2a1 on 2026-03-16 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_mode', models.CharField(choices=[('none', 'None'), ('first_failure', 'First Failure'), ('every_failure', 'Every Failure')], default='first_failure', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('one_time', 'One Time'), ('recurring', 'Recurring')], max_length=20)),
                ('timezone_mode', models.CharField(blank=True, max_length=50)),
                ('timezone_name', models.CharField(max_length=255)),
                ('interval_type', models.CharField(blank=True, choices=[('hours', 'Hours'), ('days', 'Days')], max_length=20, null=True)),
                ('interval_value', models.PositiveIntegerField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('content_mode', models.CharField(choices=[('fixed_new', 'Fixed New'), ('fixed_from_list', 'Fixed From List'), ('random_from_list', 'Random From List'), ('random_from_lists', 'Random From Lists')], max_length=30)),
                ('fixed_content', models.TextField(blank=True, null=True)),
                ('random_resolution_mode', models.CharField(blank=True, choices=[('shared', 'Shared'), ('per_account', 'Per Account')], max_length=20, null=True)),
                ('reuse_enabled', models.BooleanField(default=False)),
                ('exhaustion_behavior', models.CharField(blank=True, choices=[('stop', 'Stop'), ('skip', 'Skip'), ('reset', 'Reset')], max_length=20, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(max_length=255, unique=True)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('renewed_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('username', models.CharField(blank=True, max_length=255)),
                ('encrypted_password', models.BinaryField(blank=True, null=True)),
                ('sender_email', models.EmailField(max_length=254)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_starttls', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TweetList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationAccountState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('first_failure_notified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_state', to='core.postingaccount')),
            ],
        ),
        migrations.CreateModel(
            name='PostingAccountSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_data', models.BinaryField()),
                ('field_hash', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secret', to='core.postingaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField()),
                ('display_timezone', models.CharField(max_length=255)),
                ('schedule_version', models.PositiveIntegerField()),
                ('content_resolved', models.BooleanField(default=False)),
                ('resolved_content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('missed', 'Missed'), ('skipped', 'Skipped'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('cancel_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='core.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=255)),
                ('content_summary', models.CharField(blank=True, max_length=255)),
                ('result_status', models.CharField(blank=True, max_length=100)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=100)),
                ('occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.occurrence')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.postingaccount')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='TweetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.tweetlist')),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automatic_attempt_seq', models.PositiveIntegerField(default=1)),
                ('resolved_content', models.TextField(blank=True, null=True)),
                ('validation_ok', models.BooleanField(default=False)),
                ('post_result', models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('validation_failed', 'Validation Failed')], max_length=20, null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('external_response_meta', models.JSONField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.occurrence')),
                ('target_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.postingaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('occurrence', 'target_account', 'automatic_attempt_seq'), name='unique_occurrence_attempt')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleTargetAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.postingaccount')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_accounts', to='core.schedule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('schedule', 'account'), name='unique_schedule_account')],
            },
        ),
        migrations.CreateModel(
            name='RecurringUsageState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schedule')),
                ('tweet_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tweetentry')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('schedule', 'tweet_entry'), name='unique_recurring_usage')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSourceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_lists', to='core.schedule')),
                ('tweet_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tweetlist')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('schedule', 'tweet_list'), name='unique_schedule_list')],
            },
        ),
    ]
