# Generated by Django 5.2a1 on 2026-03-17 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='resolved_tweet_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.tweetentry'),
        ),
        migrations.AddField(
            model_name='occurrenceattempt',
            name='resolved_tweet_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.tweetentry'),
        ),
    ]
